-- DEPRECATED - Merged into 012_add_receipt_items_and_summaries.sql
-- Content: record_items.user_marked_idk BOOLEAN NOT NULL DEFAULT FALSE
-- New databases: do NOT run this file (already in 012 final schema).
